// Applications data — each application is a timeline of real events, not a table row.
// Grouped by current reality: Needs attention, In process, Awaiting response, Closed.

const APPLICATIONS_DATA = {
  active: [
    // ─── Needs attention ────────────────────────────────────────────
    {
      id: 'a01',
      title: 'Senior Product Designer',
      company: 'Linear',
      short: 'Ln',
      location: 'Remote (EU)',
      salary: '£95k–£120k',
      stage: 'Applied',
      status: 'No response · 17 days',
      group: 'attention',
      cv: 'Founding Product Designer',
      firstResponse: null,
      lastActivity: '17 days ago',
      timeline: [
        { date: '12 Mar', label: 'Applied' },
        { date: '14 Mar', label: 'Recruiter viewed profile', subtle: true },
        { date: '—',      label: 'No response in 17 days', pending: true, warn: true },
      ],
    },
    {
      id: 'a02',
      title: 'Design Lead, Growth',
      company: 'Ramp',
      short: 'Rp',
      location: 'London · Hybrid',
      salary: 'Not stated',
      stage: 'Task',
      status: 'Needs follow-up',
      group: 'attention',
      cv: 'Platform / Growth Design',
      firstResponse: '3 days',
      lastActivity: '8 days ago',
      timeline: [
        { date: '26 Feb', label: 'Applied' },
        { date: '1 Mar',  label: 'Recruiter screen' },
        { date: '6 Mar',  label: 'Hiring manager' },
        { date: '10 Mar', label: 'Task submitted' },
        { date: '—',      label: 'Awaiting review · 8 days', pending: true, warn: true },
      ],
    },
    {
      id: 'a03',
      title: 'Product Designer, Platform',
      company: 'Airtable',
      short: 'Ab',
      location: 'Remote (US)',
      salary: 'Not stated',
      stage: 'Applied',
      status: 'Awaiting response · 12 days',
      group: 'attention',
      cv: 'Generalist Product Designer',
      firstResponse: null,
      lastActivity: '12 days ago',
      timeline: [
        { date: '17 Mar', label: 'Applied' },
        { date: '—',      label: 'No response in 12 days', pending: true, warn: true },
      ],
    },

    // ─── In process ─────────────────────────────────────────────────
    {
      id: 'a04',
      title: 'Staff Designer, AI',
      company: 'Figma',
      short: 'Fg',
      location: 'Remote (UK)',
      salary: '$180k–$210k',
      stage: 'Hiring Manager',
      status: 'Interview Thu 14:00',
      group: 'progress',
      cv: 'Founding Product Designer',
      firstResponse: '2 days',
      lastActivity: '2 hours ago',
      timeline: [
        { date: '20 Mar', label: 'Applied' },
        { date: '22 Mar', label: 'Recruiter screen' },
        { date: '27 Mar', label: 'Moved to hiring manager', live: true },
        { date: '2 Apr',  label: 'Interview scheduled · Thu 14:00', upcoming: true },
      ],
    },
    {
      id: 'a05',
      title: 'Senior Product Designer',
      company: 'Stripe',
      short: 'St',
      location: 'London · Hybrid',
      salary: '£110k–£135k',
      stage: 'Panel',
      status: 'Scheduled next Tuesday',
      group: 'progress',
      cv: 'Senior Product Designer',
      firstResponse: '4 days',
      lastActivity: 'Yesterday',
      timeline: [
        { date: '8 Mar',  label: 'Applied' },
        { date: '12 Mar', label: 'Recruiter screen' },
        { date: '17 Mar', label: 'Hiring manager' },
        { date: '24 Mar', label: 'Task submitted' },
        { date: '28 Mar', label: 'Panel confirmed', live: true },
        { date: '8 Apr',  label: 'Panel · 3 interviews, one day', upcoming: true },
      ],
    },
    {
      id: 'a06',
      title: 'Product Designer II',
      company: 'Arc',
      short: 'Ar',
      location: 'New York · Hybrid',
      salary: '$170k–$195k',
      stage: 'Task',
      status: 'In progress · due Fri',
      group: 'progress',
      cv: 'Generalist Product Designer',
      firstResponse: '1 day',
      lastActivity: '4 days ago',
      timeline: [
        { date: '15 Mar', label: 'Applied' },
        { date: '16 Mar', label: 'Recruiter screen' },
        { date: '21 Mar', label: 'Hiring manager' },
        { date: '25 Mar', label: 'Take-home received', live: true },
        { date: '5 Apr',  label: 'Due Friday', upcoming: true },
      ],
    },
    {
      id: 'a07',
      title: 'Design Lead, Platform',
      company: 'Ramp',
      short: 'R2',
      location: 'Remote (US)',
      salary: '$190k–$220k',
      stage: 'Recruiter Screen',
      status: 'Scheduled Friday',
      group: 'progress',
      cv: 'Platform / Growth Design',
      firstResponse: 'Same day',
      lastActivity: '3 hours ago',
      timeline: [
        { date: '25 Mar', label: 'Applied' },
        { date: '25 Mar', label: 'Recruiter replied', subtle: true },
        { date: '29 Mar', label: 'Screen scheduled', live: true },
        { date: '5 Apr',  label: 'Recruiter screen · Fri', upcoming: true },
      ],
    },

    // ─── Awaiting response ──────────────────────────────────────────
    {
      id: 'a08',
      title: 'Senior Designer, Apps',
      company: 'Notion',
      short: 'Nt',
      location: 'San Francisco · Hybrid',
      salary: '$210k base',
      stage: 'Applied',
      status: 'Awaiting response',
      group: 'awaiting',
      cv: 'Senior Product Designer',
      firstResponse: null,
      lastActivity: '6 days ago',
      timeline: [
        { date: '23 Mar', label: 'Applied' },
        { date: '—',      label: 'No response yet', pending: true },
      ],
    },
    {
      id: 'a09',
      title: 'Product Designer, Core',
      company: 'Vercel',
      short: 'Vc',
      location: 'Remote',
      salary: '$165k–$190k',
      stage: 'Applied',
      status: 'Awaiting response',
      group: 'awaiting',
      cv: 'Generalist Product Designer',
      firstResponse: null,
      lastActivity: '4 days ago',
      timeline: [
        { date: '25 Mar', label: 'Applied' },
        { date: '—',      label: 'No response yet', pending: true },
      ],
    },
    {
      id: 'a10',
      title: 'Lead Product Designer',
      company: 'Supabase',
      short: 'Sb',
      location: 'Remote (Global)',
      salary: '$175k–$200k',
      stage: 'Applied',
      status: 'Awaiting response',
      group: 'awaiting',
      cv: 'Founding Product Designer',
      firstResponse: null,
      lastActivity: '2 days ago',
      timeline: [
        { date: '27 Mar', label: 'Applied' },
        { date: '—',      label: 'No response yet', pending: true },
      ],
    },

    // ─── Closed ─────────────────────────────────────────────────────
    {
      id: 'a11',
      title: 'Product Designer',
      company: 'Datadog',
      short: 'Dd',
      location: 'New York · On-site',
      salary: '$160k–$185k',
      stage: 'Closed',
      status: 'Role filled internally',
      closedKind: 'rejected',
      group: 'closed',
      cv: 'Senior Product Designer',
      firstResponse: '6 days',
      lastActivity: '18 days ago',
      timeline: [
        { date: '22 Feb', label: 'Applied' },
        { date: '28 Feb', label: 'Recruiter screen' },
        { date: '5 Mar',  label: 'Hiring manager' },
        { date: '14 Mar', label: 'Panel' },
        { date: '21 Mar', label: 'Final' },
        { date: '28 Mar', label: 'Rejected — role filled internally', closed: true },
      ],
    },
    {
      id: 'a12',
      title: 'Senior Designer',
      company: 'Vercel',
      short: 'V2',
      location: 'Remote',
      salary: 'Not stated',
      stage: 'Withdrawn',
      status: 'You withdrew',
      closedKind: 'withdrawn',
      group: 'closed',
      cv: 'Generalist Product Designer',
      firstResponse: '2 days',
      lastActivity: '11 days ago',
      timeline: [
        { date: '18 Mar', label: 'Applied' },
        { date: '20 Mar', label: 'Recruiter screen' },
        { date: '24 Mar', label: 'Withdrew — misaligned on comp', closed: true },
      ],
    },
    {
      id: 'a13',
      title: 'Design Lead, Canvas',
      company: 'Miro',
      short: 'Mr',
      location: 'Amsterdam · Hybrid',
      salary: '€95k–€115k',
      stage: 'Rejected',
      status: 'Rejected after HM',
      closedKind: 'rejected',
      group: 'closed',
      cv: 'Senior Product Designer',
      firstResponse: '5 days',
      lastActivity: '24 days ago',
      timeline: [
        { date: '15 Feb', label: 'Applied' },
        { date: '20 Feb', label: 'Recruiter screen' },
        { date: '1 Mar',  label: 'Hiring manager' },
        { date: '5 Mar',  label: 'Rejected after HM', closed: true },
      ],
    },
  ],

  heavy: [], // filled below

  early: [
    {
      id: 'ea01',
      title: 'Senior Product Designer',
      company: 'Linear',
      short: 'Ln',
      location: 'Remote (EU)',
      salary: '£95k–£120k',
      stage: 'Recruiter Screen',
      status: 'Scheduled Thursday',
      group: 'progress',
      cv: 'Founding Product Designer',
      firstResponse: '1 day',
      lastActivity: 'Today',
      timeline: [
        { date: '27 Mar', label: 'Applied' },
        { date: '28 Mar', label: 'Recruiter replied', subtle: true },
        { date: '29 Mar', label: 'Screen scheduled', live: true },
        { date: '4 Apr',  label: 'Recruiter screen · Thu', upcoming: true },
      ],
    },
    {
      id: 'ea02',
      title: 'Product Designer',
      company: 'Arc',
      short: 'Ar',
      location: 'Remote',
      salary: 'Not stated',
      stage: 'Applied',
      status: 'Awaiting response',
      group: 'awaiting',
      cv: 'Generalist Product Designer',
      firstResponse: null,
      lastActivity: 'Yesterday',
      timeline: [
        { date: '28 Mar', label: 'Applied' },
        { date: '—',      label: 'No response yet', pending: true },
      ],
    },
  ],
};

// Heavy = active + more in each group
APPLICATIONS_DATA.heavy = [
  ...APPLICATIONS_DATA.active,
  {
    id: 'h01',
    title: 'Head of Design',
    company: 'Replicate',
    short: 'Rc',
    location: 'Remote (Global)',
    salary: '$220k–$260k',
    stage: 'Final',
    status: 'Offer pending',
    group: 'progress',
    cv: 'Founding Product Designer',
    firstResponse: 'Same day',
    lastActivity: '1 hour ago',
    timeline: [
      { date: '1 Mar',  label: 'Applied' },
      { date: '1 Mar',  label: 'Recruiter replied', subtle: true },
      { date: '4 Mar',  label: 'Recruiter screen' },
      { date: '11 Mar', label: 'Hiring manager' },
      { date: '18 Mar', label: 'Task submitted' },
      { date: '25 Mar', label: 'Panel · 4 interviews' },
      { date: '2 Apr',  label: 'Final conversation' },
      { date: '—',      label: 'Verbal offer mentioned', live: true, upcoming: true },
    ],
  },
  {
    id: 'h02',
    title: 'Design Manager, Platform',
    company: 'Cloudflare',
    short: 'Cf',
    location: 'London · Hybrid',
    salary: '£140k–£165k',
    stage: 'Hiring Manager',
    status: 'Interview booked',
    group: 'progress',
    cv: 'Platform / Growth Design',
    firstResponse: '2 days',
    lastActivity: '3 hours ago',
    timeline: [
      { date: '18 Mar', label: 'Applied' },
      { date: '20 Mar', label: 'Recruiter screen' },
      { date: '26 Mar', label: 'Moved to HM', live: true },
      { date: '3 Apr',  label: 'HM interview', upcoming: true },
    ],
  },
  {
    id: 'h03',
    title: 'Product Designer, Billing',
    company: 'Datadog',
    short: 'D2',
    location: 'Remote (US)',
    salary: 'Not stated',
    stage: 'Applied',
    status: 'Awaiting response · 31 days',
    group: 'attention',
    cv: 'Generalist Product Designer',
    firstResponse: null,
    lastActivity: '31 days ago',
    timeline: [
      { date: '28 Feb', label: 'Applied' },
      { date: '—',      label: 'No response in 31 days', pending: true, warn: true },
    ],
  },
  {
    id: 'h04',
    title: 'Senior Designer, Growth',
    company: 'Retool',
    short: 'Rt',
    location: 'Remote (US)',
    salary: '$180k–$210k',
    stage: 'Applied',
    status: 'Awaiting response',
    group: 'awaiting',
    cv: 'Platform / Growth Design',
    firstResponse: null,
    lastActivity: '1 day ago',
    timeline: [
      { date: '30 Mar', label: 'Applied' },
      { date: '—',      label: 'No response yet', pending: true },
    ],
  },
  {
    id: 'h05',
    title: 'Senior Product Designer',
    company: 'Gusto',
    short: 'Gu',
    location: 'Remote (US)',
    salary: '$175k–$200k',
    stage: 'Rejected',
    status: 'Rejected after screen',
    closedKind: 'rejected',
    group: 'closed',
    cv: 'Senior Product Designer',
    firstResponse: '3 days',
    lastActivity: '22 days ago',
    timeline: [
      { date: '20 Feb', label: 'Applied' },
      { date: '23 Feb', label: 'Recruiter screen' },
      { date: '7 Mar',  label: 'Rejected after screen', closed: true },
    ],
  },
];

const APP_GROUPS = [
  { key: 'attention', label: 'Needs attention', hint: 'No response for 14+ days, or follow-up due' },
  { key: 'progress',  label: 'In process',      hint: 'Active interview stages' },
  { key: 'awaiting',  label: 'Awaiting response', hint: 'Applied — no reply yet' },
  { key: 'closed',    label: 'Closed',          hint: 'Rejected, withdrawn, or offer settled' },
];

const APP_LENSES = [
  { key: 'all',       label: 'All' },
  { key: 'attention', label: 'Needs attention' },
  { key: 'progress',  label: 'In process' },
  { key: 'awaiting',  label: 'Awaiting' },
  { key: 'closed',    label: 'Closed' },
];

Object.assign(window, { APPLICATIONS_DATA, APP_GROUPS, APP_LENSES });
