// Roles list data — richer than the overview's sample, grouped by "state of reality"
// Each role is a small briefing with context signals, not a table row.

const ROLES_DATA = {
  active: [
    // ─── Needs attention ──────────────────────────────────────────────
    {
      id: 'r01',
      title: 'Senior Product Designer',
      company: 'Linear',
      short: 'Ln',
      location: 'Remote (EU)',
      workModel: 'Remote',
      salary: '£95k–£120k',
      stage: 'Applied',
      subStage: 'No response · 17 days',
      decision: 'Applied',
      group: 'attention',
      updated: '17d ago',
      added: '18d ago',
      signals: ['No response in 17 days', 'Last seen active yesterday'],
      note: 'Recruiter viewed profile 2 days ago',
    },
    {
      id: 'r02',
      title: 'Design Lead, Growth',
      company: 'Ramp',
      short: 'Rp',
      location: 'London · Hybrid (3 days)',
      workModel: 'Hybrid',
      salary: 'Not stated',
      stage: 'Task',
      subStage: 'Needs follow-up',
      decision: 'Applied',
      group: 'attention',
      updated: '5d ago',
      added: '22d ago',
      signals: ['Task submitted · awaiting review', '3+ days onsite'],
      note: null,
    },
    {
      id: 'r03',
      title: 'Product Designer, Platform',
      company: 'Airtable',
      short: 'Ab',
      location: 'Remote (US)',
      workModel: 'Remote',
      salary: 'Not stated',
      stage: 'Applied',
      subStage: 'Awaiting response · 12 days',
      decision: 'Applied',
      group: 'attention',
      updated: '12d ago',
      added: '12d ago',
      signals: ['Salary not stated', 'No response in 12 days'],
      note: null,
    },

    // ─── In progress ──────────────────────────────────────────────────
    {
      id: 'r04',
      title: 'Staff Designer, AI',
      company: 'Figma',
      short: 'Fg',
      location: 'Remote (UK)',
      workModel: 'Remote',
      salary: '$180k–$210k',
      stage: 'Hiring Manager',
      subStage: 'Interview Thu 14:00',
      decision: 'Applied',
      group: 'progress',
      updated: '2h ago',
      added: '9d ago',
      signals: ['Interview scheduled', 'Moved from recruiter today'],
      note: 'Prep doc shared by recruiter',
    },
    {
      id: 'r05',
      title: 'Senior Product Designer',
      company: 'Stripe',
      short: 'St',
      location: 'London · Hybrid (2 days)',
      workModel: 'Hybrid',
      salary: '£110k–£135k',
      stage: 'Panel',
      subStage: 'Scheduled next Tuesday',
      decision: 'Applied',
      group: 'progress',
      updated: 'Yesterday',
      added: '21d ago',
      signals: ['3 interviews across one day'],
      note: null,
    },
    {
      id: 'r06',
      title: 'Product Designer II',
      company: 'Arc',
      short: 'Ar',
      location: 'New York · Hybrid (3 days)',
      workModel: 'Hybrid',
      salary: '$170k–$195k',
      stage: 'Task',
      subStage: 'In progress · due Fri',
      decision: 'Applied',
      group: 'progress',
      updated: '4d ago',
      added: '14d ago',
      signals: ['3+ days onsite', 'Take-home in progress'],
      note: null,
    },
    {
      id: 'r07',
      title: 'Design Lead, Platform',
      company: 'Ramp',
      short: 'Rp',
      location: 'Remote (US)',
      workModel: 'Remote',
      salary: '$190k–$220k',
      stage: 'Recruiter Screen',
      subStage: 'Scheduled Friday',
      decision: 'Applied',
      group: 'progress',
      updated: '3h ago',
      added: '4d ago',
      signals: null,
      note: null,
    },

    // ─── Applied (awaiting response) ──────────────────────────────────
    {
      id: 'r08',
      title: 'Senior Designer, Apps',
      company: 'Notion',
      short: 'Nt',
      location: 'San Francisco · Hybrid',
      workModel: 'Hybrid',
      salary: '$210k base',
      stage: 'Applied',
      subStage: 'Awaiting response',
      decision: 'Applied',
      group: 'applied',
      updated: '6d ago',
      added: '6d ago',
      signals: null,
      note: null,
    },
    {
      id: 'r09',
      title: 'Product Designer, Core',
      company: 'Vercel',
      short: 'Vc',
      location: 'Remote',
      workModel: 'Remote',
      salary: '$165k–$190k',
      stage: 'Applied',
      subStage: 'Awaiting response',
      decision: 'Applied',
      group: 'applied',
      updated: '4d ago',
      added: '4d ago',
      signals: null,
      note: null,
    },
    {
      id: 'r10',
      title: 'Lead Product Designer',
      company: 'Supabase',
      short: 'Sb',
      location: 'Remote (Global)',
      workModel: 'Remote',
      salary: '$175k–$200k',
      stage: 'Applied',
      subStage: 'Awaiting response',
      decision: 'Applied',
      group: 'applied',
      updated: '2d ago',
      added: '2d ago',
      signals: null,
      note: null,
    },

    // ─── Saved (not applied) ──────────────────────────────────────────
    {
      id: 'r11',
      title: 'Principal Designer, Editor',
      company: 'Raycast',
      short: 'Ry',
      location: 'Remote (EU/UK)',
      workModel: 'Remote',
      salary: '£130k–£160k',
      stage: 'Saved',
      subStage: 'Shortlisted · decide soon',
      decision: 'Saved',
      group: 'saved',
      updated: 'Yesterday',
      added: '3d ago',
      signals: ['Role closes in 4 days'],
      note: 'Looks aligned with tools work',
    },
    {
      id: 'r12',
      title: 'Senior Designer, ML Tooling',
      company: 'Hugging Face',
      short: 'Hf',
      location: 'Remote',
      workModel: 'Remote',
      salary: 'Not stated',
      stage: 'Saved',
      subStage: null,
      decision: 'Saved',
      group: 'saved',
      updated: '3d ago',
      added: '3d ago',
      signals: ['Salary not stated'],
      note: null,
    },
    {
      id: 'r13',
      title: 'Product Designer, Canvas',
      company: 'Miro',
      short: 'Mr',
      location: 'Amsterdam · Hybrid (3 days)',
      workModel: 'Hybrid',
      salary: '€85k–€105k',
      stage: 'Saved',
      subStage: null,
      decision: 'Saved',
      group: 'saved',
      updated: '5d ago',
      added: '5d ago',
      signals: ['3+ days onsite', 'Relocation required'],
      note: null,
    },

    // ─── Closed ───────────────────────────────────────────────────────
    {
      id: 'r14',
      title: 'Lead Designer, Docs',
      company: 'Notion',
      short: 'Nt',
      location: 'San Francisco',
      workModel: 'On-site',
      salary: '$210k base',
      stage: 'Skipped',
      subStage: 'Reason: location',
      decision: 'Skipped',
      group: 'closed',
      updated: '8d ago',
      added: '8d ago',
      signals: null,
      note: null,
    },
    {
      id: 'r15',
      title: 'Senior Designer',
      company: 'Vercel',
      short: 'Vc',
      location: 'Remote',
      workModel: 'Remote',
      salary: 'Not stated',
      stage: 'Skipped',
      subStage: 'Reason: no salary range',
      decision: 'Skipped',
      group: 'closed',
      updated: '11d ago',
      added: '11d ago',
      signals: null,
      note: null,
    },
    {
      id: 'r16',
      title: 'Product Designer',
      company: 'Datadog',
      short: 'Dd',
      location: 'New York · On-site',
      workModel: 'On-site',
      salary: '$160k–$185k',
      stage: 'Closed',
      subStage: 'Role filled',
      decision: 'Applied',
      group: 'closed',
      updated: '18d ago',
      added: '32d ago',
      signals: null,
      note: 'Reached final, role filled internally',
    },
  ],

  heavy: [
    // Same structure, bigger volume — reuse many from active + extras
    // (Keeping concise: reuse active set and add a few more in the key groups)
  ],

  early: [
    {
      id: 'e01',
      title: 'Senior Product Designer',
      company: 'Linear',
      short: 'Ln',
      location: 'Remote (EU)',
      workModel: 'Remote',
      salary: '£95k–£120k',
      stage: 'Recruiter Screen',
      subStage: 'Scheduled Thursday',
      decision: 'Applied',
      group: 'progress',
      updated: 'Today',
      added: '2d ago',
      signals: null,
      note: null,
    },
    {
      id: 'e02',
      title: 'Product Designer',
      company: 'Arc',
      short: 'Ar',
      location: 'Remote',
      workModel: 'Remote',
      salary: 'Not stated',
      stage: 'Applied',
      subStage: 'Awaiting response',
      decision: 'Applied',
      group: 'applied',
      updated: 'Yesterday',
      added: 'Yesterday',
      signals: ['Salary not stated'],
      note: null,
    },
    {
      id: 'e03',
      title: 'Staff Designer, AI',
      company: 'Figma',
      short: 'Fg',
      location: 'Remote (UK)',
      workModel: 'Remote',
      salary: '$180k–$210k',
      stage: 'Saved',
      subStage: null,
      decision: 'Saved',
      group: 'saved',
      updated: '2d ago',
      added: '2d ago',
      signals: null,
      note: null,
    },
    {
      id: 'e04',
      title: 'Senior Designer',
      company: 'Raycast',
      short: 'Ry',
      location: 'Remote (EU/UK)',
      workModel: 'Remote',
      salary: '£130k–£160k',
      stage: 'Saved',
      subStage: null,
      decision: 'Saved',
      group: 'saved',
      updated: '3d ago',
      added: '3d ago',
      signals: null,
      note: null,
    },
    {
      id: 'e05',
      title: 'Product Designer, Core',
      company: 'Supabase',
      short: 'Sb',
      location: 'Remote',
      workModel: 'Remote',
      salary: '$175k–$200k',
      stage: 'Saved',
      subStage: null,
      decision: 'Saved',
      group: 'saved',
      updated: '4d ago',
      added: '4d ago',
      signals: null,
      note: null,
    },
  ],
};

// Build heavy from active + extras
ROLES_DATA.heavy = [
  ...ROLES_DATA.active,
  {
    id: 'h01',
    title: 'Head of Design',
    company: 'Replicate',
    short: 'Rp',
    location: 'Remote (Global)',
    workModel: 'Remote',
    salary: '$220k–$260k',
    stage: 'Final',
    subStage: 'Offer pending',
    decision: 'Applied',
    group: 'progress',
    updated: '1h ago',
    added: '28d ago',
    signals: ['Offer expected this week'],
    note: 'Verbal offer mentioned on last call',
  },
  {
    id: 'h02',
    title: 'Design Manager, Platform',
    company: 'Cloudflare',
    short: 'Cf',
    location: 'London · Hybrid (3 days)',
    workModel: 'Hybrid',
    salary: '£140k–£165k',
    stage: 'Hiring Manager',
    subStage: 'In progress',
    decision: 'Applied',
    group: 'progress',
    updated: '3h ago',
    added: '11d ago',
    signals: ['3+ days onsite'],
    note: null,
  },
  {
    id: 'h03',
    title: 'Senior Designer, Growth',
    company: 'Retool',
    short: 'Rt',
    location: 'Remote (US)',
    workModel: 'Remote',
    salary: '$180k–$210k',
    stage: 'Applied',
    subStage: 'Awaiting response',
    decision: 'Applied',
    group: 'applied',
    updated: '1d ago',
    added: '1d ago',
    signals: null,
    note: null,
  },
  {
    id: 'h04',
    title: 'Product Designer, Billing',
    company: 'Datadog',
    short: 'Dd',
    location: 'Remote (US)',
    workModel: 'Remote',
    salary: 'Not stated',
    stage: 'Applied',
    subStage: 'Awaiting response · 31 days',
    decision: 'Applied',
    group: 'attention',
    updated: '31d ago',
    added: '31d ago',
    signals: ['No response in 31 days', 'Salary not stated'],
    note: null,
  },
];

const ROLE_GROUPS = [
  { key: 'attention', label: 'Needs attention', hint: 'No response, stalled, or closing soon' },
  { key: 'progress',  label: 'In progress',     hint: 'Active interview stages' },
  { key: 'applied',   label: 'Applied',         hint: 'Awaiting response' },
  { key: 'saved',     label: 'Saved',           hint: 'Not applied yet' },
  { key: 'closed',    label: 'Closed',          hint: 'Skipped or ended' },
];

const FILTER_LENSES = [
  { key: 'all',       label: 'All' },
  { key: 'attention', label: 'Needs attention' },
  { key: 'progress',  label: 'In process' },
  { key: 'applied',   label: 'Applied' },
  { key: 'saved',     label: 'Saved' },
  { key: 'closed',    label: 'Closed' },
];

Object.assign(window, { ROLES_DATA, ROLE_GROUPS, FILTER_LENSES });
