// Recruiters — a record of interactions over time.
// Grouped by interaction quality / recency, not by data structure.
// Each recruiter is a small relationship summary, not a contact row.

const RECRUITER_GROUPS = [
  {
    key: 'active',
    label: 'Active conversations',
    hint: 'Recent replies, ongoing processes',
  },
  {
    key: 'quiet',
    label: 'Recent but inactive',
    hint: 'Contacted recently, no movement yet',
  },
  {
    key: 'noise',
    label: 'No response or low signal',
    hint: 'Ghosted, or roles that weren’t a fit',
  },
  {
    key: 'closed',
    label: 'Closed interactions',
    hint: 'Finished, filled, or no longer relevant',
  },
];

const RECRUITER_LENSES = [
  { key: 'all',    label: 'Everyone' },
  { key: 'active', label: 'Active' },
  { key: 'quiet',  label: 'Quiet' },
  { key: 'noise',  label: 'Low signal' },
  { key: 'closed', label: 'Closed' },
];

const RECRUITERS_DATA = {
  active: [
    // ─── Active conversations ──────────────────────────────────────
    {
      id: 'rc01',
      name: 'Amara Okafor',
      short: 'AO',
      company: 'Linear',
      companyNote: 'Internal · Talent',
      type: 'Internal',
      source: 'LinkedIn',
      status: 'In conversation',
      group: 'active',
      lastContact: '2d ago',
      introduced: 1,
      reachedInterview: 1,
      summary: [
        'Introduced 1 role',
        '1 reached interview stage',
        'Last contact 2 days ago',
      ],
      outcomes: ['Led to interview'],
      roles: [
        { title: 'Senior Product Designer', company: 'Linear' },
      ],
      timeline: [
        { label: 'Reached out',        when: '12 Mar' },
        { label: 'Shared role',        when: '12 Mar' },
        { label: 'Recruiter screen',   when: '18 Mar' },
        { label: 'Hiring manager',     when: '26 Mar' },
      ],
      note: 'Clear briefs, shares salary up-front.',
    },
    {
      id: 'rc02',
      name: 'Daniel Reeves',
      short: 'DR',
      company: 'Signal Search',
      companyNote: 'Agency · Design',
      type: 'Agency',
      source: 'Referral',
      status: 'Active',
      group: 'active',
      lastContact: 'Yesterday',
      introduced: 3,
      reachedInterview: 1,
      summary: [
        'Introduced 3 roles',
        '1 reached interview stage',
        'Last contact yesterday',
      ],
      outcomes: ['Led to interview', 'Declined 2 (not relevant)'],
      roles: [
        { title: 'Design Lead, Platform', company: 'Ramp' },
        { title: 'Staff Designer, AI',    company: 'Figma' },
      ],
      rolesMore: 1,
      timeline: [
        { label: 'Reached out',     when: '04 Mar' },
        { label: 'Shared 3 roles',  when: '06 Mar' },
        { label: 'Intro call',      when: '09 Mar' },
        { label: 'Interview at Ramp', when: '24 Mar' },
      ],
      note: 'Understands the brief. Follows up without pushing.',
    },
    {
      id: 'rc03',
      name: 'Priya Shah',
      short: 'PS',
      company: 'Stripe',
      companyNote: 'Internal · Design',
      type: 'Internal',
      source: 'Email',
      status: 'In conversation',
      group: 'active',
      lastContact: '5d ago',
      introduced: 1,
      reachedInterview: 1,
      summary: [
        'Introduced 1 role',
        '1 reached panel stage',
        'Last contact 5 days ago',
      ],
      outcomes: ['Led to interview'],
      roles: [
        { title: 'Product Designer', company: 'Stripe' },
      ],
      timeline: [
        { label: 'Reached out',       when: '02 Mar' },
        { label: 'Shared role',       when: '02 Mar' },
        { label: 'Recruiter screen',  when: '08 Mar' },
        { label: 'Panel scheduled',   when: '28 Mar' },
      ],
      note: 'Friendly, detail-oriented. Answers questions in writing.',
    },

    // ─── Recent but inactive ──────────────────────────────────────
    {
      id: 'rc04',
      name: 'Marcus Bell',
      short: 'MB',
      company: 'Aperture Talent',
      companyNote: 'Agency',
      type: 'Agency',
      source: 'LinkedIn',
      status: 'Active',
      group: 'quiet',
      lastContact: '9d ago',
      introduced: 2,
      reachedInterview: 0,
      summary: [
        'Introduced 2 roles',
        'No interviews yet',
        'Last contact 9 days ago',
      ],
      outcomes: ['Waiting on client feedback'],
      roles: [
        { title: 'Senior Designer', company: 'Vercel' },
        { title: 'Design Lead',     company: 'Retool' },
      ],
      timeline: [
        { label: 'Reached out',   when: '21 Feb' },
        { label: 'Shared 2 roles', when: '24 Feb' },
        { label: 'Sent CV',       when: '26 Feb' },
      ],
      note: 'Waiting to hear back from both clients.',
    },
    {
      id: 'rc05',
      name: 'Elena Costa',
      short: 'EC',
      company: 'Figma',
      companyNote: 'Internal · Design Hiring',
      type: 'Internal',
      source: 'LinkedIn',
      status: 'Active',
      group: 'quiet',
      lastContact: '11d ago',
      introduced: 1,
      reachedInterview: 0,
      summary: [
        'Introduced 1 role',
        'Applied, no movement',
        'Last contact 11 days ago',
      ],
      outcomes: ['Awaiting recruiter screen'],
      roles: [
        { title: 'Staff Designer, AI', company: 'Figma' },
      ],
      timeline: [
        { label: 'Reached out', when: '18 Feb' },
        { label: 'Shared role', when: '18 Feb' },
        { label: 'Applied',     when: '21 Feb' },
      ],
      note: 'Said she’d come back “in a couple of weeks”.',
    },

    // ─── No response / low signal ──────────────────────────────────
    {
      id: 'rc06',
      name: 'Jackson Pryce',
      short: 'JP',
      company: 'Triangle Group',
      companyNote: 'Agency',
      type: 'Agency',
      source: 'LinkedIn',
      status: 'No response',
      group: 'noise',
      lastContact: '22d ago',
      introduced: 1,
      reachedInterview: 0,
      summary: [
        'Introduced 1 role',
        'No reply to follow-up',
        'Last contact 22 days ago',
      ],
      outcomes: ['No response'],
      roles: [
        { title: 'Design Manager', company: 'undisclosed' },
      ],
      timeline: [
        { label: 'Reached out',  when: '02 Feb' },
        { label: 'Replied',      when: '03 Feb' },
        { label: 'Sent follow-up', when: '16 Feb' },
        { label: 'No response',  when: '—' },
      ],
      note: 'Generic pitch, wouldn’t share company name upfront.',
    },
    {
      id: 'rc07',
      name: 'Simone Vargas',
      short: 'SV',
      company: 'Hallmark Search',
      companyNote: 'Agency',
      type: 'Agency',
      source: 'Email',
      status: 'No response',
      group: 'noise',
      lastContact: '1mo ago',
      introduced: 0,
      reachedInterview: 0,
      summary: [
        'Cold outreach',
        'Roles were Director-level, not a fit',
        'Didn’t follow up',
      ],
      outcomes: ['Not relevant roles'],
      roles: [],
      timeline: [
        { label: 'Reached out', when: '22 Jan' },
        { label: 'Declined politely', when: '23 Jan' },
      ],
      note: 'Out of scope — pitching Director of Design roles.',
    },

    // ─── Closed interactions ──────────────────────────────────────
    {
      id: 'rc08',
      name: 'Theo Lindqvist',
      short: 'TL',
      company: 'Arc',
      companyNote: 'Internal · People',
      type: 'Internal',
      source: 'Referral',
      status: 'Closed',
      group: 'closed',
      lastContact: '6w ago',
      introduced: 1,
      reachedInterview: 1,
      summary: [
        'Introduced 1 role',
        'Reached final stage',
        'Role filled internally',
      ],
      outcomes: ['Role already filled'],
      roles: [
        { title: 'Product Designer II', company: 'Arc' },
      ],
      timeline: [
        { label: 'Reached out',    when: '08 Jan' },
        { label: 'Recruiter screen', when: '14 Jan' },
        { label: 'Hiring manager', when: '22 Jan' },
        { label: 'Role filled',    when: '04 Feb' },
      ],
      note: 'Kept me informed throughout. Offered to reconnect later.',
    },
  ],

  heavy: [
    {
      id: 'rc01',
      name: 'Amara Okafor', short: 'AO', company: 'Linear', companyNote: 'Internal · Talent',
      type: 'Internal', source: 'LinkedIn', status: 'In conversation', group: 'active',
      lastContact: '1h ago', introduced: 2, reachedInterview: 2,
      summary: ['Introduced 2 roles', '2 reached interview stage', 'Last contact 1h ago'],
      outcomes: ['Led to interview'],
      roles: [{ title: 'Senior Product Designer', company: 'Linear' }, { title: 'Design Lead', company: 'Linear' }],
      timeline: [
        { label: 'Reached out', when: '12 Mar' },
        { label: 'Shared 2 roles', when: '13 Mar' },
        { label: 'Panel scheduled', when: 'Today' },
      ],
      note: 'One of the clearest processes I’ve been through.',
    },
    {
      id: 'rc02',
      name: 'Daniel Reeves', short: 'DR', company: 'Signal Search', companyNote: 'Agency · Design',
      type: 'Agency', source: 'Referral', status: 'Active', group: 'active',
      lastContact: 'Yesterday', introduced: 6, reachedInterview: 2,
      summary: ['Introduced 6 roles', '2 reached interview stage', 'Last contact yesterday'],
      outcomes: ['Led to interview', 'Declined 3 (not relevant)'],
      roles: [
        { title: 'Design Lead, Platform', company: 'Ramp' },
        { title: 'Staff Designer, AI', company: 'Figma' },
      ],
      rolesMore: 4,
      timeline: [
        { label: 'Reached out', when: '04 Feb' },
        { label: 'Shared 6 roles', when: 'Ongoing' },
        { label: 'Ramp interview', when: '24 Mar' },
        { label: 'Figma screen', when: '01 Apr' },
      ],
      note: 'Best recruiter in my pipeline right now.',
    },
    {
      id: 'rc03',
      name: 'Priya Shah', short: 'PS', company: 'Stripe', companyNote: 'Internal · Design',
      type: 'Internal', source: 'Email', status: 'In conversation', group: 'active',
      lastContact: '3d ago', introduced: 1, reachedInterview: 1,
      summary: ['Introduced 1 role', 'Offer pending', 'Last contact 3 days ago'],
      outcomes: ['Offer pending'],
      roles: [{ title: 'Product Designer', company: 'Stripe' }],
      timeline: [
        { label: 'Reached out', when: '02 Mar' },
        { label: 'Panel done', when: '28 Mar' },
        { label: 'References', when: '05 Apr' },
        { label: 'Offer incoming', when: '—' },
      ],
      note: 'Offer conversation active this week.',
    },
    {
      id: 'rc04',
      name: 'Marcus Bell', short: 'MB', company: 'Aperture Talent', companyNote: 'Agency',
      type: 'Agency', source: 'LinkedIn', status: 'Active', group: 'active',
      lastContact: '6d ago', introduced: 4, reachedInterview: 1,
      summary: ['Introduced 4 roles', '1 reached interview', 'Last contact 6 days ago'],
      outcomes: ['Led to interview', 'Declined 2 (not relevant)'],
      roles: [
        { title: 'Senior Designer', company: 'Vercel' },
        { title: 'Design Lead', company: 'Retool' },
      ],
      rolesMore: 2,
      timeline: [
        { label: 'Reached out', when: '21 Jan' },
        { label: 'Shared 4 roles', when: 'Ongoing' },
        { label: 'Retool screen', when: '18 Mar' },
      ],
      note: 'Volume over precision, but reliable.',
    },
    {
      id: 'rc05',
      name: 'Elena Costa', short: 'EC', company: 'Figma', companyNote: 'Internal',
      type: 'Internal', source: 'LinkedIn', status: 'Active', group: 'quiet',
      lastContact: '9d ago', introduced: 1, reachedInterview: 0,
      summary: ['Introduced 1 role', 'Applied, no movement', 'Last contact 9 days ago'],
      outcomes: ['Awaiting recruiter screen'],
      roles: [{ title: 'Staff Designer, AI', company: 'Figma' }],
      timeline: [
        { label: 'Reached out', when: '18 Feb' },
        { label: 'Applied', when: '21 Feb' },
      ],
      note: 'Promised update by end of last week.',
    },
    {
      id: 'rc06',
      name: 'Robin Chen', short: 'RC', company: 'Notion', companyNote: 'Internal',
      type: 'Internal', source: 'LinkedIn', status: 'Active', group: 'quiet',
      lastContact: '12d ago', introduced: 1, reachedInterview: 0,
      summary: ['Introduced 1 role', 'Location mismatch', 'Last contact 12 days ago'],
      outcomes: ['Paused — location'],
      roles: [{ title: 'Lead Designer, Docs', company: 'Notion' }],
      timeline: [
        { label: 'Reached out', when: '10 Feb' },
        { label: 'Declined (SF only)', when: '12 Feb' },
      ],
      note: 'Kept door open for remote roles.',
    },
    {
      id: 'rc07',
      name: 'Jackson Pryce', short: 'JP', company: 'Triangle Group', companyNote: 'Agency',
      type: 'Agency', source: 'LinkedIn', status: 'No response', group: 'noise',
      lastContact: '22d ago', introduced: 1, reachedInterview: 0,
      summary: ['Introduced 1 role', 'No reply to follow-up', 'Last contact 22 days ago'],
      outcomes: ['No response'],
      roles: [{ title: 'Design Manager', company: 'undisclosed' }],
      timeline: [
        { label: 'Reached out', when: '02 Feb' },
        { label: 'Follow-up', when: '16 Feb' },
        { label: 'No response', when: '—' },
      ],
      note: 'Wouldn’t share company name upfront.',
    },
    {
      id: 'rc08',
      name: 'Simone Vargas', short: 'SV', company: 'Hallmark Search', companyNote: 'Agency',
      type: 'Agency', source: 'Email', status: 'No response', group: 'noise',
      lastContact: '1mo ago', introduced: 0, reachedInterview: 0,
      summary: ['Cold outreach', 'Director roles — not a fit', 'Didn’t follow up'],
      outcomes: ['Not relevant roles'],
      roles: [],
      timeline: [
        { label: 'Reached out', when: '22 Jan' },
        { label: 'Declined politely', when: '23 Jan' },
      ],
      note: 'Pitched Director roles; out of scope.',
    },
    {
      id: 'rc09',
      name: 'Maya Whitfield', short: 'MW', company: 'Bracket Search', companyNote: 'Agency',
      type: 'Agency', source: 'LinkedIn', status: 'No response', group: 'noise',
      lastContact: '5w ago', introduced: 0, reachedInterview: 0,
      summary: ['Cold outreach', 'Vague brief', 'No reply after pushback'],
      outcomes: ['No response'],
      roles: [],
      timeline: [
        { label: 'Reached out', when: '12 Jan' },
        { label: 'Asked for details', when: '13 Jan' },
        { label: 'No response', when: '—' },
      ],
      note: 'Couldn’t share salary band or company.',
    },
    {
      id: 'rc10',
      name: 'Theo Lindqvist', short: 'TL', company: 'Arc', companyNote: 'Internal · People',
      type: 'Internal', source: 'Referral', status: 'Closed', group: 'closed',
      lastContact: '6w ago', introduced: 1, reachedInterview: 1,
      summary: ['Introduced 1 role', 'Reached final stage', 'Role filled internally'],
      outcomes: ['Role already filled'],
      roles: [{ title: 'Product Designer II', company: 'Arc' }],
      timeline: [
        { label: 'Reached out', when: '08 Jan' },
        { label: 'Recruiter screen', when: '14 Jan' },
        { label: 'Hiring manager', when: '22 Jan' },
        { label: 'Role filled', when: '04 Feb' },
      ],
      note: 'Offered to reconnect later.',
    },
    {
      id: 'rc11',
      name: 'Helena Ortiz', short: 'HO', company: 'Airtable', companyNote: 'Internal',
      type: 'Internal', source: 'Email', status: 'Closed', group: 'closed',
      lastContact: '2mo ago', introduced: 1, reachedInterview: 0,
      summary: ['Introduced 1 role', 'Withdrew before screen', 'Closed'],
      outcomes: ['Withdrew — scope shift'],
      roles: [{ title: 'Senior Designer, Apps', company: 'Airtable' }],
      timeline: [
        { label: 'Reached out', when: '04 Jan' },
        { label: 'Scope change', when: '11 Jan' },
        { label: 'Withdrew', when: '15 Jan' },
      ],
      note: 'Scope shifted to heavy research; not a fit.',
    },
  ],

  early: [
    {
      id: 'rc01',
      name: 'Amara Okafor', short: 'AO', company: 'Linear', companyNote: 'Internal · Talent',
      type: 'Internal', source: 'LinkedIn', status: 'In conversation', group: 'active',
      lastContact: 'Today', introduced: 1, reachedInterview: 0,
      summary: ['Introduced 1 role', 'Recruiter screen scheduled', 'Last contact today'],
      outcomes: ['Recruiter screen booked'],
      roles: [{ title: 'Senior Product Designer', company: 'Linear' }],
      timeline: [
        { label: 'Reached out', when: 'Mon' },
        { label: 'Shared role', when: 'Mon' },
        { label: 'Screen scheduled', when: 'Thu' },
      ],
      note: 'First recruiter contact this cycle.',
    },
    {
      id: 'rc02',
      name: 'Marcus Bell', short: 'MB', company: 'Aperture Talent', companyNote: 'Agency',
      type: 'Agency', source: 'LinkedIn', status: 'Active', group: 'quiet',
      lastContact: '4d ago', introduced: 1, reachedInterview: 0,
      summary: ['Introduced 1 role', 'Sent CV, waiting', 'Last contact 4 days ago'],
      outcomes: ['Waiting on client feedback'],
      roles: [{ title: 'Senior Designer', company: 'Vercel' }],
      timeline: [
        { label: 'Reached out', when: 'Last wk' },
        { label: 'Sent CV', when: '4d ago' },
      ],
      note: 'Pleasant, a little slow.',
    },
  ],
};

Object.assign(window, { RECRUITERS_DATA, RECRUITER_GROUPS, RECRUITER_LENSES });
